Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  # If err, see also the issue #3083, https://github.com/hashicorp/vagrant/issues/3083
  config.vm.network :private_network, type: "dhcp", ip: "192.168.111.0"
  config.vm.synced_folder ".", "/home/vagrant/test"
end

