Vagrant.configure("2") do |config|
  config.vm.define "master" do |conf|
    conf.vm.box = "ubuntu/trusty64"
    conf.vm.network "private_network", ip: "192.168.111.2", virtualbox__intnet: "mynet"
  end

  config.vm.define "client" do |conf|
    conf.vm.box = "ubuntu/trusty64"
    conf.vm.network "private_network", ip: "192.168.111.100", virtualbox__intnet: "mynet"
    conf.vm.synced_folder ".", "/home/vagrant/test"
    # see also https://www.vagrantup.com/docs/networking/public_network.html#default-router
    gw = "192.168.111.2"
    conf.vm.provision "shell",
      run: "always",
      inline: "route add default gw #{gw}"

    conf.vm.provision "shell",
      run: "always",
      inline: "eval `route -n | awk '{ if ($8 ==\"eth0\" && $2 != \"0.0.0.0\") print \"route del default gw \" $2; }'`"
  end

end
